# Generated by Django 4.1.7 on 2023-09-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='auth_provider',
            field=models.CharField(default='email', max_length=100),
        ),
    ]
