# Generated by Django 4.1.7 on 2023-07-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
